name: "Generate OG Image"
description: "Helps users generate a OG Image from frontmatter"
author: "Agney"
branding:
  icon: "share-2"
  color: "orange"
inputs:
  description: "Path to place generated assets"
  default: "demo/"
runs:
  using: "docker"
  image: "Dockerfile"
