name: "Generate OG Image"
description: "Helps users generate a OG Image from frontmatter"
author: "Agney"
branding:
  icon: "share-2"
  color: "orange"
inputs:
  path:
    description: "Path to place generated assets"
    default: "demo/"
  commitMsg:
    description: "commit message to be shown when adding image"
    default: "just some wholesome content. yo all!"
runs:
  using: "docker"
  image: "Dockerfile"
