name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  myInput:              # change this
    description: 'input description here'
    default: 'CHANGE DEFAULT VALUE?'
runs:
  using: 'node12'
  main: 'dist/index.js'
  name: generate-meta-images
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
