name: "Generate OG Image"
description: "Helps users generate a OG Image from frontmatter"
author: "Agney"
branding:
  icon: "share-2"
  color: "orange"
inputs:
  path:
    description: "Path to place generated assets"
    default: "demo/"
  commitMsg:
    description: "commit message to be shown when adding image"
    default: "just some wholesome content. yo all!"
  background-color:
    description: "background color for image"
    default: "#ffffff"
  font-color:
    description: "font color for image"
    default: "#000000"
  componentUrl:
    description: "URL for web component"
    default: "https://unpkg.com/@agney/og-image-element@0.1.1"
runs:
  using: "docker"
  image: "Dockerfile"
